// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module PC(	// src/main/scala/core/PC.scala:6:7
  input         clock,	// <stdin>:4:11
                reset,	// <stdin>:5:11
  input  [31:0] io_pc_in,	// src/main/scala/core/PC.scala:7:14
  input         io_stall,	// src/main/scala/core/PC.scala:7:14
  output [31:0] io_pc_out	// src/main/scala/core/PC.scala:7:14
);

  reg [31:0] pcReg;	// src/main/scala/core/PC.scala:13:22
  always @(posedge clock) begin	// <stdin>:4:11
    if (reset)	// <stdin>:4:11
      pcReg <= 32'h0;	// src/main/scala/core/PC.scala:13:22
    else if (io_stall) begin	// src/main/scala/core/PC.scala:7:14
    end
    else	// src/main/scala/core/PC.scala:7:14
      pcReg <= io_pc_in;	// src/main/scala/core/PC.scala:13:22
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/core/PC.scala:6:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/core/PC.scala:6:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/core/PC.scala:6:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/core/PC.scala:6:7
      automatic logic [31:0] _RANDOM[0:0];	// src/main/scala/core/PC.scala:6:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/core/PC.scala:6:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/core/PC.scala:6:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/core/PC.scala:6:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// src/main/scala/core/PC.scala:6:7
        pcReg = _RANDOM[/*Zero width*/ 1'b0];	// src/main/scala/core/PC.scala:6:7, :13:22
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/core/PC.scala:6:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/core/PC.scala:6:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_pc_out = pcReg;	// src/main/scala/core/PC.scala:6:7, :13:22
endmodule

module InstructionMemory(	// src/main/scala/core/InstructionMemeory.scala:7:7
  input  [31:0] io_address,	// src/main/scala/core/InstructionMemeory.scala:8:14
  output [31:0] io_data_out	// src/main/scala/core/InstructionMemeory.scala:8:14
);

  wire [1023:0][31:0] _GEN =
    '{32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'h0,
      32'hB50633,
      32'h1400593,
      32'hA00513};	// src/main/scala/core/InstructionMemeory.scala:28:15
  assign io_data_out = _GEN[io_address[11:2]];	// <stdin>:1045:29, src/main/scala/core/InstructionMemeory.scala:7:7, :28:{15,33}
endmodule

module RegisterFile(	// src/main/scala/core/RegisterFile.scala:6:7
  input         clock,	// <stdin>:1049:11
                reset,	// <stdin>:1050:11
                io_regWrite,	// src/main/scala/core/RegisterFile.scala:7:14
  input  [4:0]  io_ra1,	// src/main/scala/core/RegisterFile.scala:7:14
                io_ra2,	// src/main/scala/core/RegisterFile.scala:7:14
                io_wa,	// src/main/scala/core/RegisterFile.scala:7:14
  input  [31:0] io_wd,	// src/main/scala/core/RegisterFile.scala:7:14
  output [31:0] io_rd1,	// src/main/scala/core/RegisterFile.scala:7:14
                io_rd2	// src/main/scala/core/RegisterFile.scala:7:14
);

  reg  [31:0]       registers_0;	// src/main/scala/core/RegisterFile.scala:17:26
  reg  [31:0]       registers_1;	// src/main/scala/core/RegisterFile.scala:17:26
  reg  [31:0]       registers_2;	// src/main/scala/core/RegisterFile.scala:17:26
  reg  [31:0]       registers_3;	// src/main/scala/core/RegisterFile.scala:17:26
  reg  [31:0]       registers_4;	// src/main/scala/core/RegisterFile.scala:17:26
  reg  [31:0]       registers_5;	// src/main/scala/core/RegisterFile.scala:17:26
  reg  [31:0]       registers_6;	// src/main/scala/core/RegisterFile.scala:17:26
  reg  [31:0]       registers_7;	// src/main/scala/core/RegisterFile.scala:17:26
  reg  [31:0]       registers_8;	// src/main/scala/core/RegisterFile.scala:17:26
  reg  [31:0]       registers_9;	// src/main/scala/core/RegisterFile.scala:17:26
  reg  [31:0]       registers_10;	// src/main/scala/core/RegisterFile.scala:17:26
  reg  [31:0]       registers_11;	// src/main/scala/core/RegisterFile.scala:17:26
  reg  [31:0]       registers_12;	// src/main/scala/core/RegisterFile.scala:17:26
  reg  [31:0]       registers_13;	// src/main/scala/core/RegisterFile.scala:17:26
  reg  [31:0]       registers_14;	// src/main/scala/core/RegisterFile.scala:17:26
  reg  [31:0]       registers_15;	// src/main/scala/core/RegisterFile.scala:17:26
  reg  [31:0]       registers_16;	// src/main/scala/core/RegisterFile.scala:17:26
  reg  [31:0]       registers_17;	// src/main/scala/core/RegisterFile.scala:17:26
  reg  [31:0]       registers_18;	// src/main/scala/core/RegisterFile.scala:17:26
  reg  [31:0]       registers_19;	// src/main/scala/core/RegisterFile.scala:17:26
  reg  [31:0]       registers_20;	// src/main/scala/core/RegisterFile.scala:17:26
  reg  [31:0]       registers_21;	// src/main/scala/core/RegisterFile.scala:17:26
  reg  [31:0]       registers_22;	// src/main/scala/core/RegisterFile.scala:17:26
  reg  [31:0]       registers_23;	// src/main/scala/core/RegisterFile.scala:17:26
  reg  [31:0]       registers_24;	// src/main/scala/core/RegisterFile.scala:17:26
  reg  [31:0]       registers_25;	// src/main/scala/core/RegisterFile.scala:17:26
  reg  [31:0]       registers_26;	// src/main/scala/core/RegisterFile.scala:17:26
  reg  [31:0]       registers_27;	// src/main/scala/core/RegisterFile.scala:17:26
  reg  [31:0]       registers_28;	// src/main/scala/core/RegisterFile.scala:17:26
  reg  [31:0]       registers_29;	// src/main/scala/core/RegisterFile.scala:17:26
  reg  [31:0]       registers_30;	// src/main/scala/core/RegisterFile.scala:17:26
  reg  [31:0]       registers_31;	// src/main/scala/core/RegisterFile.scala:17:26
  wire [31:0][31:0] _GEN =
    {{registers_31},
     {registers_30},
     {registers_29},
     {registers_28},
     {registers_27},
     {registers_26},
     {registers_25},
     {registers_24},
     {registers_23},
     {registers_22},
     {registers_21},
     {registers_20},
     {registers_19},
     {registers_18},
     {registers_17},
     {registers_16},
     {registers_15},
     {registers_14},
     {registers_13},
     {registers_12},
     {registers_11},
     {registers_10},
     {registers_9},
     {registers_8},
     {registers_7},
     {registers_6},
     {registers_5},
     {registers_4},
     {registers_3},
     {registers_2},
     {registers_1},
     {registers_0}};	// src/main/scala/core/RegisterFile.scala:17:26, :19:16
  always @(posedge clock) begin	// <stdin>:1049:11
    if (reset) begin	// <stdin>:1049:11
      registers_0 <= 32'h0;	// src/main/scala/core/RegisterFile.scala:17:{26,34}
      registers_1 <= 32'h0;	// src/main/scala/core/RegisterFile.scala:17:{26,34}
      registers_2 <= 32'h0;	// src/main/scala/core/RegisterFile.scala:17:{26,34}
      registers_3 <= 32'h0;	// src/main/scala/core/RegisterFile.scala:17:{26,34}
      registers_4 <= 32'h0;	// src/main/scala/core/RegisterFile.scala:17:{26,34}
      registers_5 <= 32'h0;	// src/main/scala/core/RegisterFile.scala:17:{26,34}
      registers_6 <= 32'h0;	// src/main/scala/core/RegisterFile.scala:17:{26,34}
      registers_7 <= 32'h0;	// src/main/scala/core/RegisterFile.scala:17:{26,34}
      registers_8 <= 32'h0;	// src/main/scala/core/RegisterFile.scala:17:{26,34}
      registers_9 <= 32'h0;	// src/main/scala/core/RegisterFile.scala:17:{26,34}
      registers_10 <= 32'h0;	// src/main/scala/core/RegisterFile.scala:17:{26,34}
      registers_11 <= 32'h0;	// src/main/scala/core/RegisterFile.scala:17:{26,34}
      registers_12 <= 32'h0;	// src/main/scala/core/RegisterFile.scala:17:{26,34}
      registers_13 <= 32'h0;	// src/main/scala/core/RegisterFile.scala:17:{26,34}
      registers_14 <= 32'h0;	// src/main/scala/core/RegisterFile.scala:17:{26,34}
      registers_15 <= 32'h0;	// src/main/scala/core/RegisterFile.scala:17:{26,34}
      registers_16 <= 32'h0;	// src/main/scala/core/RegisterFile.scala:17:{26,34}
      registers_17 <= 32'h0;	// src/main/scala/core/RegisterFile.scala:17:{26,34}
      registers_18 <= 32'h0;	// src/main/scala/core/RegisterFile.scala:17:{26,34}
      registers_19 <= 32'h0;	// src/main/scala/core/RegisterFile.scala:17:{26,34}
      registers_20 <= 32'h0;	// src/main/scala/core/RegisterFile.scala:17:{26,34}
      registers_21 <= 32'h0;	// src/main/scala/core/RegisterFile.scala:17:{26,34}
      registers_22 <= 32'h0;	// src/main/scala/core/RegisterFile.scala:17:{26,34}
      registers_23 <= 32'h0;	// src/main/scala/core/RegisterFile.scala:17:{26,34}
      registers_24 <= 32'h0;	// src/main/scala/core/RegisterFile.scala:17:{26,34}
      registers_25 <= 32'h0;	// src/main/scala/core/RegisterFile.scala:17:{26,34}
      registers_26 <= 32'h0;	// src/main/scala/core/RegisterFile.scala:17:{26,34}
      registers_27 <= 32'h0;	// src/main/scala/core/RegisterFile.scala:17:{26,34}
      registers_28 <= 32'h0;	// src/main/scala/core/RegisterFile.scala:17:{26,34}
      registers_29 <= 32'h0;	// src/main/scala/core/RegisterFile.scala:17:{26,34}
      registers_30 <= 32'h0;	// src/main/scala/core/RegisterFile.scala:17:{26,34}
      registers_31 <= 32'h0;	// src/main/scala/core/RegisterFile.scala:17:{26,34}
    end
    else begin	// <stdin>:1049:11
      automatic logic _GEN_0 = io_regWrite & (|io_wa);	// src/main/scala/core/RegisterFile.scala:22:{20,29}
      if (_GEN_0 & ~(|io_wa))	// src/main/scala/core/RegisterFile.scala:17:26, :22:{20,29,38}, :23:22
        registers_0 <= io_wd;	// src/main/scala/core/RegisterFile.scala:17:26
      if (_GEN_0 & io_wa == 5'h1)	// src/main/scala/core/RegisterFile.scala:6:7, :17:26, :22:{20,38}, :23:22
        registers_1 <= io_wd;	// src/main/scala/core/RegisterFile.scala:17:26
      if (_GEN_0 & io_wa == 5'h2)	// src/main/scala/core/RegisterFile.scala:6:7, :17:26, :22:{20,38}, :23:22
        registers_2 <= io_wd;	// src/main/scala/core/RegisterFile.scala:17:26
      if (_GEN_0 & io_wa == 5'h3)	// src/main/scala/core/RegisterFile.scala:6:7, :17:26, :22:{20,38}, :23:22
        registers_3 <= io_wd;	// src/main/scala/core/RegisterFile.scala:17:26
      if (_GEN_0 & io_wa == 5'h4)	// src/main/scala/core/RegisterFile.scala:6:7, :17:26, :22:{20,38}, :23:22
        registers_4 <= io_wd;	// src/main/scala/core/RegisterFile.scala:17:26
      if (_GEN_0 & io_wa == 5'h5)	// src/main/scala/core/RegisterFile.scala:6:7, :17:26, :22:{20,38}, :23:22
        registers_5 <= io_wd;	// src/main/scala/core/RegisterFile.scala:17:26
      if (_GEN_0 & io_wa == 5'h6)	// src/main/scala/core/RegisterFile.scala:6:7, :17:26, :22:{20,38}, :23:22
        registers_6 <= io_wd;	// src/main/scala/core/RegisterFile.scala:17:26
      if (_GEN_0 & io_wa == 5'h7)	// src/main/scala/core/RegisterFile.scala:6:7, :17:26, :22:{20,38}, :23:22
        registers_7 <= io_wd;	// src/main/scala/core/RegisterFile.scala:17:26
      if (_GEN_0 & io_wa == 5'h8)	// src/main/scala/core/RegisterFile.scala:6:7, :17:26, :22:{20,38}, :23:22
        registers_8 <= io_wd;	// src/main/scala/core/RegisterFile.scala:17:26
      if (_GEN_0 & io_wa == 5'h9)	// src/main/scala/core/RegisterFile.scala:6:7, :17:26, :22:{20,38}, :23:22
        registers_9 <= io_wd;	// src/main/scala/core/RegisterFile.scala:17:26
      if (_GEN_0 & io_wa == 5'hA)	// src/main/scala/core/RegisterFile.scala:6:7, :17:26, :22:{20,38}, :23:22
        registers_10 <= io_wd;	// src/main/scala/core/RegisterFile.scala:17:26
      if (_GEN_0 & io_wa == 5'hB)	// src/main/scala/core/RegisterFile.scala:6:7, :17:26, :22:{20,38}, :23:22
        registers_11 <= io_wd;	// src/main/scala/core/RegisterFile.scala:17:26
      if (_GEN_0 & io_wa == 5'hC)	// src/main/scala/core/RegisterFile.scala:6:7, :17:26, :22:{20,38}, :23:22
        registers_12 <= io_wd;	// src/main/scala/core/RegisterFile.scala:17:26
      if (_GEN_0 & io_wa == 5'hD)	// src/main/scala/core/RegisterFile.scala:6:7, :17:26, :22:{20,38}, :23:22
        registers_13 <= io_wd;	// src/main/scala/core/RegisterFile.scala:17:26
      if (_GEN_0 & io_wa == 5'hE)	// src/main/scala/core/RegisterFile.scala:6:7, :17:26, :22:{20,38}, :23:22
        registers_14 <= io_wd;	// src/main/scala/core/RegisterFile.scala:17:26
      if (_GEN_0 & io_wa == 5'hF)	// src/main/scala/core/RegisterFile.scala:6:7, :17:26, :22:{20,38}, :23:22
        registers_15 <= io_wd;	// src/main/scala/core/RegisterFile.scala:17:26
      if (_GEN_0 & io_wa == 5'h10)	// src/main/scala/core/RegisterFile.scala:6:7, :17:26, :22:{20,38}, :23:22
        registers_16 <= io_wd;	// src/main/scala/core/RegisterFile.scala:17:26
      if (_GEN_0 & io_wa == 5'h11)	// src/main/scala/core/RegisterFile.scala:6:7, :17:26, :22:{20,38}, :23:22
        registers_17 <= io_wd;	// src/main/scala/core/RegisterFile.scala:17:26
      if (_GEN_0 & io_wa == 5'h12)	// src/main/scala/core/RegisterFile.scala:6:7, :17:26, :22:{20,38}, :23:22
        registers_18 <= io_wd;	// src/main/scala/core/RegisterFile.scala:17:26
      if (_GEN_0 & io_wa == 5'h13)	// src/main/scala/core/RegisterFile.scala:6:7, :17:26, :22:{20,38}, :23:22
        registers_19 <= io_wd;	// src/main/scala/core/RegisterFile.scala:17:26
      if (_GEN_0 & io_wa == 5'h14)	// src/main/scala/core/RegisterFile.scala:6:7, :17:26, :22:{20,38}, :23:22
        registers_20 <= io_wd;	// src/main/scala/core/RegisterFile.scala:17:26
      if (_GEN_0 & io_wa == 5'h15)	// src/main/scala/core/RegisterFile.scala:6:7, :17:26, :22:{20,38}, :23:22
        registers_21 <= io_wd;	// src/main/scala/core/RegisterFile.scala:17:26
      if (_GEN_0 & io_wa == 5'h16)	// src/main/scala/core/RegisterFile.scala:6:7, :17:26, :22:{20,38}, :23:22
        registers_22 <= io_wd;	// src/main/scala/core/RegisterFile.scala:17:26
      if (_GEN_0 & io_wa == 5'h17)	// src/main/scala/core/RegisterFile.scala:6:7, :17:26, :22:{20,38}, :23:22
        registers_23 <= io_wd;	// src/main/scala/core/RegisterFile.scala:17:26
      if (_GEN_0 & io_wa == 5'h18)	// src/main/scala/core/RegisterFile.scala:6:7, :17:26, :22:{20,38}, :23:22
        registers_24 <= io_wd;	// src/main/scala/core/RegisterFile.scala:17:26
      if (_GEN_0 & io_wa == 5'h19)	// src/main/scala/core/RegisterFile.scala:6:7, :17:26, :22:{20,38}, :23:22
        registers_25 <= io_wd;	// src/main/scala/core/RegisterFile.scala:17:26
      if (_GEN_0 & io_wa == 5'h1A)	// src/main/scala/core/RegisterFile.scala:6:7, :17:26, :22:{20,38}, :23:22
        registers_26 <= io_wd;	// src/main/scala/core/RegisterFile.scala:17:26
      if (_GEN_0 & io_wa == 5'h1B)	// src/main/scala/core/RegisterFile.scala:6:7, :17:26, :22:{20,38}, :23:22
        registers_27 <= io_wd;	// src/main/scala/core/RegisterFile.scala:17:26
      if (_GEN_0 & io_wa == 5'h1C)	// src/main/scala/core/RegisterFile.scala:6:7, :17:26, :22:{20,38}, :23:22
        registers_28 <= io_wd;	// src/main/scala/core/RegisterFile.scala:17:26
      if (_GEN_0 & io_wa == 5'h1D)	// src/main/scala/core/RegisterFile.scala:6:7, :17:26, :22:{20,38}, :23:22
        registers_29 <= io_wd;	// src/main/scala/core/RegisterFile.scala:17:26
      if (_GEN_0 & io_wa == 5'h1E)	// src/main/scala/core/RegisterFile.scala:6:7, :17:26, :22:{20,38}, :23:22
        registers_30 <= io_wd;	// src/main/scala/core/RegisterFile.scala:17:26
      if (_GEN_0 & (&io_wa))	// src/main/scala/core/RegisterFile.scala:17:26, :22:{20,38}, :23:22
        registers_31 <= io_wd;	// src/main/scala/core/RegisterFile.scala:17:26
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/core/RegisterFile.scala:6:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/core/RegisterFile.scala:6:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/core/RegisterFile.scala:6:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/core/RegisterFile.scala:6:7
      automatic logic [31:0] _RANDOM[0:31];	// src/main/scala/core/RegisterFile.scala:6:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/core/RegisterFile.scala:6:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/core/RegisterFile.scala:6:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/core/RegisterFile.scala:6:7
        for (logic [5:0] i = 6'h0; i < 6'h20; i += 6'h1) begin
          _RANDOM[i[4:0]] = `RANDOM;	// src/main/scala/core/RegisterFile.scala:6:7
        end	// src/main/scala/core/RegisterFile.scala:6:7
        registers_0 = _RANDOM[5'h0];	// src/main/scala/core/RegisterFile.scala:6:7, :17:26
        registers_1 = _RANDOM[5'h1];	// src/main/scala/core/RegisterFile.scala:6:7, :17:26
        registers_2 = _RANDOM[5'h2];	// src/main/scala/core/RegisterFile.scala:6:7, :17:26
        registers_3 = _RANDOM[5'h3];	// src/main/scala/core/RegisterFile.scala:6:7, :17:26
        registers_4 = _RANDOM[5'h4];	// src/main/scala/core/RegisterFile.scala:6:7, :17:26
        registers_5 = _RANDOM[5'h5];	// src/main/scala/core/RegisterFile.scala:6:7, :17:26
        registers_6 = _RANDOM[5'h6];	// src/main/scala/core/RegisterFile.scala:6:7, :17:26
        registers_7 = _RANDOM[5'h7];	// src/main/scala/core/RegisterFile.scala:6:7, :17:26
        registers_8 = _RANDOM[5'h8];	// src/main/scala/core/RegisterFile.scala:6:7, :17:26
        registers_9 = _RANDOM[5'h9];	// src/main/scala/core/RegisterFile.scala:6:7, :17:26
        registers_10 = _RANDOM[5'hA];	// src/main/scala/core/RegisterFile.scala:6:7, :17:26
        registers_11 = _RANDOM[5'hB];	// src/main/scala/core/RegisterFile.scala:6:7, :17:26
        registers_12 = _RANDOM[5'hC];	// src/main/scala/core/RegisterFile.scala:6:7, :17:26
        registers_13 = _RANDOM[5'hD];	// src/main/scala/core/RegisterFile.scala:6:7, :17:26
        registers_14 = _RANDOM[5'hE];	// src/main/scala/core/RegisterFile.scala:6:7, :17:26
        registers_15 = _RANDOM[5'hF];	// src/main/scala/core/RegisterFile.scala:6:7, :17:26
        registers_16 = _RANDOM[5'h10];	// src/main/scala/core/RegisterFile.scala:6:7, :17:26
        registers_17 = _RANDOM[5'h11];	// src/main/scala/core/RegisterFile.scala:6:7, :17:26
        registers_18 = _RANDOM[5'h12];	// src/main/scala/core/RegisterFile.scala:6:7, :17:26
        registers_19 = _RANDOM[5'h13];	// src/main/scala/core/RegisterFile.scala:6:7, :17:26
        registers_20 = _RANDOM[5'h14];	// src/main/scala/core/RegisterFile.scala:6:7, :17:26
        registers_21 = _RANDOM[5'h15];	// src/main/scala/core/RegisterFile.scala:6:7, :17:26
        registers_22 = _RANDOM[5'h16];	// src/main/scala/core/RegisterFile.scala:6:7, :17:26
        registers_23 = _RANDOM[5'h17];	// src/main/scala/core/RegisterFile.scala:6:7, :17:26
        registers_24 = _RANDOM[5'h18];	// src/main/scala/core/RegisterFile.scala:6:7, :17:26
        registers_25 = _RANDOM[5'h19];	// src/main/scala/core/RegisterFile.scala:6:7, :17:26
        registers_26 = _RANDOM[5'h1A];	// src/main/scala/core/RegisterFile.scala:6:7, :17:26
        registers_27 = _RANDOM[5'h1B];	// src/main/scala/core/RegisterFile.scala:6:7, :17:26
        registers_28 = _RANDOM[5'h1C];	// src/main/scala/core/RegisterFile.scala:6:7, :17:26
        registers_29 = _RANDOM[5'h1D];	// src/main/scala/core/RegisterFile.scala:6:7, :17:26
        registers_30 = _RANDOM[5'h1E];	// src/main/scala/core/RegisterFile.scala:6:7, :17:26
        registers_31 = _RANDOM[5'h1F];	// src/main/scala/core/RegisterFile.scala:6:7, :17:26
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/core/RegisterFile.scala:6:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/core/RegisterFile.scala:6:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_rd1 = io_ra1 == 5'h0 ? 32'h0 : _GEN[io_ra1];	// src/main/scala/core/RegisterFile.scala:6:7, :17:34, :19:{16,24}
  assign io_rd2 = io_ra2 == 5'h0 ? 32'h0 : _GEN[io_ra2];	// src/main/scala/core/RegisterFile.scala:6:7, :17:34, :19:16, :20:{16,24}
endmodule

module Control_Unit(	// src/main/scala/core/Control_Unit.scala:7:7
  input  [31:0] io_instruction,	// src/main/scala/core/Control_Unit.scala:8:14
  input         io_stall,	// src/main/scala/core/Control_Unit.scala:8:14
  output        io_ALU_src,	// src/main/scala/core/Control_Unit.scala:8:14
                io_Reg_write,	// src/main/scala/core/Control_Unit.scala:8:14
                io_Mem_write,	// src/main/scala/core/Control_Unit.scala:8:14
                io_MemRead,	// src/main/scala/core/Control_Unit.scala:8:14
  output [3:0]  io_ALU_op,	// src/main/scala/core/Control_Unit.scala:8:14
  output        io_MemtoReg	// src/main/scala/core/Control_Unit.scala:8:14
);

  wire _GEN = io_instruction[6:0] == 7'h33;	// src/main/scala/core/Control_Unit.scala:21:30, :40:20
  wire _GEN_0 = io_instruction[6:0] == 7'h3;	// src/main/scala/core/Control_Unit.scala:21:30, :40:20
  wire io_MemRead_0 = ~io_stall & ~_GEN & _GEN_0;	// src/main/scala/core/Control_Unit.scala:34:16, :39:{8,19}, :40:20
  wire _GEN_1 = io_instruction[6:0] == 7'h23;	// src/main/scala/core/Control_Unit.scala:21:30, :40:20
  wire _GEN_2 = _GEN | _GEN_0;	// src/main/scala/core/Control_Unit.scala:33:16, :40:20
  wire _GEN_3 = io_instruction[6:0] == 7'h13;	// src/main/scala/core/Control_Unit.scala:21:30, :40:20
  wire _GEN_4 = _GEN_0 | _GEN_1;	// src/main/scala/core/Control_Unit.scala:40:20, :47:22, :54:22
  assign io_ALU_src = ~io_stall & ~_GEN & (_GEN_4 | _GEN_3);	// src/main/scala/core/Control_Unit.scala:7:7, :31:16, :34:16, :39:{8,19}, :40:20, :47:22, :54:22
  assign io_Reg_write = ~io_stall & (_GEN_2 | ~_GEN_1 & _GEN_3);	// src/main/scala/core/Control_Unit.scala:7:7, :32:16, :33:16, :39:{8,19}, :40:20, :43:22, :48:22
  assign io_Mem_write = ~io_stall & ~_GEN_2 & _GEN_1;	// src/main/scala/core/Control_Unit.scala:7:7, :33:16, :39:{8,19}, :40:20
  assign io_MemRead = io_MemRead_0;	// src/main/scala/core/Control_Unit.scala:7:7, :34:16, :39:19, :40:20
  assign io_ALU_op =
    io_stall
      ? 4'h0
      : _GEN
          ? {io_instruction[14:12], io_instruction[30]}
          : _GEN_4
              ? 4'h2
              : _GEN_3
                  ? {io_instruction[14:12], 1'h0}
                  : {3'h0, io_instruction[6:0] == 7'h63};	// src/main/scala/core/Control_Unit.scala:7:7, :21:30, :22:30, :23:30, :31:16, :37:16, :39:19, :40:20, :44:{22,28}, :47:22, :51:22, :54:22, :56:22, :61:{22,28}, :65:19
  assign io_MemtoReg = io_MemRead_0;	// src/main/scala/core/Control_Unit.scala:7:7, :34:16, :39:19, :40:20
endmodule

module ImmGen(	// src/main/scala/core/ImmGen.scala:7:7
  input  [31:0] io_instr,	// src/main/scala/core/ImmGen.scala:8:14
  output [31:0] io_imm	// src/main/scala/core/ImmGen.scala:8:14
);

  assign io_imm =
    io_instr[6:0] == 7'h13
      ? {{20{io_instr[31]}}, io_instr[31:20]}
      : io_instr[6:0] == 7'h3
          ? {{20{io_instr[31]}}, io_instr[31:20]}
          : io_instr[6:0] == 7'h23
              ? {{20{io_instr[31]}}, io_instr[31:25], io_instr[11:7]}
              : io_instr[6:0] == 7'h63
                  ? {{20{io_instr[31]}},
                     io_instr[7],
                     io_instr[30:25],
                     io_instr[11:8],
                     1'h0}
                  : 32'h0;	// src/main/scala/core/ImmGen.scala:7:7, :13:24, :16:10, :18:18, :22:{14,20,25,38,53}, :28:{14,20,25,38,53}, :34:{14,20,25,38,53,71}, :40:{14,20,25,38,53,66,84}
endmodule

module ALU(	// src/main/scala/core/ALU.scala:7:7
  input  [31:0] io_op1,	// src/main/scala/core/ALU.scala:8:14
                io_op2,	// src/main/scala/core/ALU.scala:8:14
  input  [3:0]  io_alu_control,	// src/main/scala/core/ALU.scala:8:14
  output [31:0] io_alu_result	// src/main/scala/core/ALU.scala:8:14
);

  assign io_alu_result =
    io_alu_control == 4'h0
      ? io_op1 + io_op2
      : io_alu_control == 4'h2
          ? io_op1 + io_op2
          : io_alu_control == 4'h1
              ? io_op1 - io_op2
              : io_alu_control == 4'h4
                  ? {31'h0, $signed(io_op1) < $signed(io_op2)}
                  : io_alu_control == 4'hC
                      ? io_op1 | io_op2
                      : io_alu_control == 4'hE ? io_op1 & io_op2 : 32'h0;	// src/main/scala/core/ALU.scala:7:7, :16:17, :18:26, :19:{29,39}, :20:{29,39}, :21:{29,39}, :22:{29,43}, :23:{30,40}, :24:{30,40}
endmodule

// VCS coverage exclude_file
module memory_1024x32(	// src/main/scala/core/Data_Memory.scala:15:19
  input  [9:0]  R0_addr,
  input         R0_en,
                R0_clk,
  output [31:0] R0_data,
  input  [9:0]  W0_addr,
  input         W0_en,
                W0_clk,
  input  [31:0] W0_data
);

  reg [31:0] Memory[0:1023];	// src/main/scala/core/Data_Memory.scala:15:19
  always @(posedge W0_clk) begin	// src/main/scala/core/Data_Memory.scala:15:19
    if (W0_en & 1'h1)	// src/main/scala/core/Data_Memory.scala:15:19
      Memory[W0_addr] <= W0_data;	// src/main/scala/core/Data_Memory.scala:15:19
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_	// src/main/scala/core/Data_Memory.scala:15:19
    reg [31:0] _RANDOM_MEM;	// src/main/scala/core/Data_Memory.scala:15:19
    initial begin	// src/main/scala/core/Data_Memory.scala:15:19
      `INIT_RANDOM_PROLOG_	// src/main/scala/core/Data_Memory.scala:15:19
      `ifdef RANDOMIZE_MEM_INIT	// src/main/scala/core/Data_Memory.scala:15:19
        for (logic [10:0] i = 11'h0; i < 11'h400; i += 11'h1) begin
          _RANDOM_MEM = `RANDOM;	// src/main/scala/core/Data_Memory.scala:15:19
          Memory[i[9:0]] = _RANDOM_MEM;	// src/main/scala/core/Data_Memory.scala:15:19
        end	// src/main/scala/core/Data_Memory.scala:15:19
      `endif // RANDOMIZE_MEM_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign R0_data = R0_en ? Memory[R0_addr] : 32'bx;	// src/main/scala/core/Data_Memory.scala:15:19
endmodule

module Data_Memory(	// src/main/scala/core/Data_Memory.scala:6:7
  input         clock,	// <stdin>:1245:11
  input  [31:0] io_Daddress,	// src/main/scala/core/Data_Memory.scala:7:14
                io_write_data,	// src/main/scala/core/Data_Memory.scala:7:14
  input         io_MemWrite,	// src/main/scala/core/Data_Memory.scala:7:14
  output [31:0] io_read_data	// src/main/scala/core/Data_Memory.scala:7:14
);

  memory_1024x32 memory_ext (	// src/main/scala/core/Data_Memory.scala:15:19
    .R0_addr (io_Daddress[11:2]),	// src/main/scala/core/Data_Memory.scala:21:{25,37}
    .R0_en   (1'h1),	// src/main/scala/core/Data_Memory.scala:6:7
    .R0_clk  (clock),
    .R0_data (io_read_data),
    .W0_addr (io_Daddress[11:2]),	// src/main/scala/core/Data_Memory.scala:18:{11,23}
    .W0_en   (io_MemWrite),
    .W0_clk  (clock),
    .W0_data (io_write_data)
  );
endmodule

module pipeline_reg_if_id(	// src/main/scala/core/Pipeline_Registers.scala:6:7
  input         clock,	// <stdin>:1261:11
                reset,	// <stdin>:1262:11
                io_stall,	// src/main/scala/core/Pipeline_Registers.scala:7:14
  input  [31:0] io_instruction_in,	// src/main/scala/core/Pipeline_Registers.scala:7:14
  output [31:0] io_instruction_out	// src/main/scala/core/Pipeline_Registers.scala:7:14
);

  reg [31:0] instruction_out_reg;	// src/main/scala/core/Pipeline_Registers.scala:17:36
  always @(posedge clock) begin	// <stdin>:1261:11
    if (reset)	// <stdin>:1261:11
      instruction_out_reg <= 32'h0;	// src/main/scala/core/Pipeline_Registers.scala:16:27, :17:36
    else if (io_stall) begin	// src/main/scala/core/Pipeline_Registers.scala:7:14
    end
    else	// src/main/scala/core/Pipeline_Registers.scala:7:14
      instruction_out_reg <= io_instruction_in;	// src/main/scala/core/Pipeline_Registers.scala:17:36
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/core/Pipeline_Registers.scala:6:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/core/Pipeline_Registers.scala:6:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/core/Pipeline_Registers.scala:6:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/core/Pipeline_Registers.scala:6:7
      automatic logic [31:0] _RANDOM[0:1];	// src/main/scala/core/Pipeline_Registers.scala:6:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/core/Pipeline_Registers.scala:6:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/core/Pipeline_Registers.scala:6:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/core/Pipeline_Registers.scala:6:7
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          _RANDOM[i[0]] = `RANDOM;	// src/main/scala/core/Pipeline_Registers.scala:6:7
        end	// src/main/scala/core/Pipeline_Registers.scala:6:7
        instruction_out_reg = _RANDOM[1'h1];	// src/main/scala/core/Pipeline_Registers.scala:6:7, :17:36
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/core/Pipeline_Registers.scala:6:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/core/Pipeline_Registers.scala:6:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_instruction_out = instruction_out_reg;	// src/main/scala/core/Pipeline_Registers.scala:6:7, :17:36
endmodule

module pipeline_reg_id_ex(	// src/main/scala/core/Pipeline_Registers.scala:36:7
  input         clock,	// <stdin>:1283:11
                reset,	// <stdin>:1284:11
                io_flush,	// src/main/scala/core/Pipeline_Registers.scala:37:14
  input  [31:0] io_read_data1_in,	// src/main/scala/core/Pipeline_Registers.scala:37:14
                io_read_data2_in,	// src/main/scala/core/Pipeline_Registers.scala:37:14
                io_sign_ext_imm_in,	// src/main/scala/core/Pipeline_Registers.scala:37:14
  input  [4:0]  io_rd_in,	// src/main/scala/core/Pipeline_Registers.scala:37:14
                io_rs1_in,	// src/main/scala/core/Pipeline_Registers.scala:37:14
                io_rs2_in,	// src/main/scala/core/Pipeline_Registers.scala:37:14
  input         io_ALU_src_in,	// src/main/scala/core/Pipeline_Registers.scala:37:14
  input  [3:0]  io_ALU_op_in,	// src/main/scala/core/Pipeline_Registers.scala:37:14
  input         io_mem_write_in,	// src/main/scala/core/Pipeline_Registers.scala:37:14
                io_mem_read_in,	// src/main/scala/core/Pipeline_Registers.scala:37:14
                io_reg_write_in,	// src/main/scala/core/Pipeline_Registers.scala:37:14
                io_mem_to_reg_in,	// src/main/scala/core/Pipeline_Registers.scala:37:14
  output [31:0] io_read_data1_out,	// src/main/scala/core/Pipeline_Registers.scala:37:14
                io_read_data2_out,	// src/main/scala/core/Pipeline_Registers.scala:37:14
                io_sign_ext_imm_out,	// src/main/scala/core/Pipeline_Registers.scala:37:14
  output [4:0]  io_rd_out,	// src/main/scala/core/Pipeline_Registers.scala:37:14
                io_rs1_out,	// src/main/scala/core/Pipeline_Registers.scala:37:14
                io_rs2_out,	// src/main/scala/core/Pipeline_Registers.scala:37:14
  output        io_ALU_src_out,	// src/main/scala/core/Pipeline_Registers.scala:37:14
  output [3:0]  io_ALU_op_out,	// src/main/scala/core/Pipeline_Registers.scala:37:14
  output        io_mem_write_out,	// src/main/scala/core/Pipeline_Registers.scala:37:14
                io_mem_read_out,	// src/main/scala/core/Pipeline_Registers.scala:37:14
                io_reg_write_out,	// src/main/scala/core/Pipeline_Registers.scala:37:14
                io_mem_to_reg_out	// src/main/scala/core/Pipeline_Registers.scala:37:14
);

  reg [31:0] rd1;	// src/main/scala/core/Pipeline_Registers.scala:71:29
  reg [31:0] rd2;	// src/main/scala/core/Pipeline_Registers.scala:72:29
  reg [31:0] imm;	// src/main/scala/core/Pipeline_Registers.scala:73:29
  reg [4:0]  rd;	// src/main/scala/core/Pipeline_Registers.scala:74:29
  reg [4:0]  rs1;	// src/main/scala/core/Pipeline_Registers.scala:75:29
  reg [4:0]  rs2;	// src/main/scala/core/Pipeline_Registers.scala:76:29
  reg        alu_src;	// src/main/scala/core/Pipeline_Registers.scala:77:29
  reg [3:0]  alu_op;	// src/main/scala/core/Pipeline_Registers.scala:78:29
  reg        mem_w;	// src/main/scala/core/Pipeline_Registers.scala:79:29
  reg        mem_r;	// src/main/scala/core/Pipeline_Registers.scala:80:29
  reg        reg_w;	// src/main/scala/core/Pipeline_Registers.scala:81:29
  reg        m2r;	// src/main/scala/core/Pipeline_Registers.scala:82:29
  always @(posedge clock) begin	// <stdin>:1283:11
    if (reset) begin	// <stdin>:1283:11
      rd1 <= 32'h0;	// src/main/scala/core/Pipeline_Registers.scala:70:29, :71:29
      rd2 <= 32'h0;	// src/main/scala/core/Pipeline_Registers.scala:70:29, :72:29
      imm <= 32'h0;	// src/main/scala/core/Pipeline_Registers.scala:70:29, :73:29
      rd <= 5'h0;	// src/main/scala/core/Pipeline_Registers.scala:74:29
      rs1 <= 5'h0;	// src/main/scala/core/Pipeline_Registers.scala:74:29, :75:29
      rs2 <= 5'h0;	// src/main/scala/core/Pipeline_Registers.scala:74:29, :76:29
      alu_src <= 1'h0;	// src/main/scala/core/Pipeline_Registers.scala:77:29
      alu_op <= 4'h0;	// src/main/scala/core/Pipeline_Registers.scala:78:29
      mem_w <= 1'h0;	// src/main/scala/core/Pipeline_Registers.scala:77:29, :79:29
      mem_r <= 1'h0;	// src/main/scala/core/Pipeline_Registers.scala:77:29, :80:29
      reg_w <= 1'h0;	// src/main/scala/core/Pipeline_Registers.scala:77:29, :81:29
      m2r <= 1'h0;	// src/main/scala/core/Pipeline_Registers.scala:77:29, :82:29
    end
    else begin	// <stdin>:1283:11
      rd1 <= io_flush ? 32'h0 : io_read_data1_in;	// src/main/scala/core/Pipeline_Registers.scala:70:29, :71:29, :85:18, :86:20, :90:25
      rd2 <= io_flush ? 32'h0 : io_read_data2_in;	// src/main/scala/core/Pipeline_Registers.scala:70:29, :72:29, :85:18, :86:32, :90:50
      imm <= io_flush ? 32'h0 : io_sign_ext_imm_in;	// src/main/scala/core/Pipeline_Registers.scala:70:29, :73:29, :85:18, :86:44, :90:75
      rd <= io_flush ? 5'h0 : io_rd_in;	// src/main/scala/core/Pipeline_Registers.scala:74:29, :85:18, :86:55, :91:8
      rs1 <= io_flush ? 5'h0 : io_rs1_in;	// src/main/scala/core/Pipeline_Registers.scala:74:29, :75:29, :85:18, :86:67, :91:25
      rs2 <= io_flush ? 5'h0 : io_rs2_in;	// src/main/scala/core/Pipeline_Registers.scala:74:29, :76:29, :85:18, :86:79, :91:43
      alu_src <= ~io_flush & io_ALU_src_in;	// src/main/scala/core/Pipeline_Registers.scala:77:29, :85:18, :87:13, :91:65
      alu_op <= io_flush ? 4'h0 : io_ALU_op_in;	// src/main/scala/core/Pipeline_Registers.scala:78:29, :85:18, :87:32, :92:12
      mem_w <= ~io_flush & io_mem_write_in;	// src/main/scala/core/Pipeline_Registers.scala:79:29, :85:18, :87:{13,46}, :91:65, :92:35
      mem_r <= ~io_flush & io_mem_read_in;	// src/main/scala/core/Pipeline_Registers.scala:80:29, :85:18, :87:{13,64}, :91:65, :92:61
      reg_w <= ~io_flush & io_reg_write_in;	// src/main/scala/core/Pipeline_Registers.scala:81:29, :85:18, :87:{13,82}, :91:65, :93:11
      m2r <= ~io_flush & io_mem_to_reg_in;	// src/main/scala/core/Pipeline_Registers.scala:82:29, :85:18, :87:13, :88:9, :91:65, :93:35
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/core/Pipeline_Registers.scala:36:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/core/Pipeline_Registers.scala:36:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/core/Pipeline_Registers.scala:36:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/core/Pipeline_Registers.scala:36:7
      automatic logic [31:0] _RANDOM[0:4];	// src/main/scala/core/Pipeline_Registers.scala:36:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/core/Pipeline_Registers.scala:36:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/core/Pipeline_Registers.scala:36:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/core/Pipeline_Registers.scala:36:7
        for (logic [2:0] i = 3'h0; i < 3'h5; i += 3'h1) begin
          _RANDOM[i] = `RANDOM;	// src/main/scala/core/Pipeline_Registers.scala:36:7
        end	// src/main/scala/core/Pipeline_Registers.scala:36:7
        rd1 = _RANDOM[3'h1];	// src/main/scala/core/Pipeline_Registers.scala:36:7, :71:29
        rd2 = _RANDOM[3'h2];	// src/main/scala/core/Pipeline_Registers.scala:36:7, :72:29
        imm = _RANDOM[3'h3];	// src/main/scala/core/Pipeline_Registers.scala:36:7, :73:29
        rd = _RANDOM[3'h4][4:0];	// src/main/scala/core/Pipeline_Registers.scala:36:7, :74:29
        rs1 = _RANDOM[3'h4][9:5];	// src/main/scala/core/Pipeline_Registers.scala:36:7, :74:29, :75:29
        rs2 = _RANDOM[3'h4][14:10];	// src/main/scala/core/Pipeline_Registers.scala:36:7, :74:29, :76:29
        alu_src = _RANDOM[3'h4][15];	// src/main/scala/core/Pipeline_Registers.scala:36:7, :74:29, :77:29
        alu_op = _RANDOM[3'h4][19:16];	// src/main/scala/core/Pipeline_Registers.scala:36:7, :74:29, :78:29
        mem_w = _RANDOM[3'h4][20];	// src/main/scala/core/Pipeline_Registers.scala:36:7, :74:29, :79:29
        mem_r = _RANDOM[3'h4][21];	// src/main/scala/core/Pipeline_Registers.scala:36:7, :74:29, :80:29
        reg_w = _RANDOM[3'h4][22];	// src/main/scala/core/Pipeline_Registers.scala:36:7, :74:29, :81:29
        m2r = _RANDOM[3'h4][23];	// src/main/scala/core/Pipeline_Registers.scala:36:7, :74:29, :82:29
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/core/Pipeline_Registers.scala:36:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/core/Pipeline_Registers.scala:36:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_read_data1_out = rd1;	// src/main/scala/core/Pipeline_Registers.scala:36:7, :71:29
  assign io_read_data2_out = rd2;	// src/main/scala/core/Pipeline_Registers.scala:36:7, :72:29
  assign io_sign_ext_imm_out = imm;	// src/main/scala/core/Pipeline_Registers.scala:36:7, :73:29
  assign io_rd_out = rd;	// src/main/scala/core/Pipeline_Registers.scala:36:7, :74:29
  assign io_rs1_out = rs1;	// src/main/scala/core/Pipeline_Registers.scala:36:7, :75:29
  assign io_rs2_out = rs2;	// src/main/scala/core/Pipeline_Registers.scala:36:7, :76:29
  assign io_ALU_src_out = alu_src;	// src/main/scala/core/Pipeline_Registers.scala:36:7, :77:29
  assign io_ALU_op_out = alu_op;	// src/main/scala/core/Pipeline_Registers.scala:36:7, :78:29
  assign io_mem_write_out = mem_w;	// src/main/scala/core/Pipeline_Registers.scala:36:7, :79:29
  assign io_mem_read_out = mem_r;	// src/main/scala/core/Pipeline_Registers.scala:36:7, :80:29
  assign io_reg_write_out = reg_w;	// src/main/scala/core/Pipeline_Registers.scala:36:7, :81:29
  assign io_mem_to_reg_out = m2r;	// src/main/scala/core/Pipeline_Registers.scala:36:7, :82:29
endmodule

module pipeline_reg_ex_mem(	// src/main/scala/core/Pipeline_Registers.scala:102:7
  input         clock,	// <stdin>:1347:11
                reset,	// <stdin>:1348:11
  input  [31:0] io_alu_result_in,	// src/main/scala/core/Pipeline_Registers.scala:103:14
                io_write_data_in,	// src/main/scala/core/Pipeline_Registers.scala:103:14
  input  [4:0]  io_rd_in,	// src/main/scala/core/Pipeline_Registers.scala:103:14
  input         io_mem_write_in,	// src/main/scala/core/Pipeline_Registers.scala:103:14
                io_reg_write_in,	// src/main/scala/core/Pipeline_Registers.scala:103:14
                io_mem_to_reg_in,	// src/main/scala/core/Pipeline_Registers.scala:103:14
  output [31:0] io_alu_result_out,	// src/main/scala/core/Pipeline_Registers.scala:103:14
                io_write_data_out,	// src/main/scala/core/Pipeline_Registers.scala:103:14
  output [4:0]  io_rd_out,	// src/main/scala/core/Pipeline_Registers.scala:103:14
  output        io_mem_write_out,	// src/main/scala/core/Pipeline_Registers.scala:103:14
                io_reg_write_out,	// src/main/scala/core/Pipeline_Registers.scala:103:14
                io_mem_to_reg_out	// src/main/scala/core/Pipeline_Registers.scala:103:14
);

  reg [31:0] io_alu_result_out_REG;	// src/main/scala/core/Pipeline_Registers.scala:121:31
  reg [31:0] io_write_data_out_REG;	// src/main/scala/core/Pipeline_Registers.scala:122:31
  reg [4:0]  io_rd_out_REG;	// src/main/scala/core/Pipeline_Registers.scala:123:31
  reg        io_mem_write_out_REG;	// src/main/scala/core/Pipeline_Registers.scala:125:31
  reg        io_reg_write_out_REG;	// src/main/scala/core/Pipeline_Registers.scala:126:31
  reg        io_mem_to_reg_out_REG;	// src/main/scala/core/Pipeline_Registers.scala:127:31
  always @(posedge clock) begin	// <stdin>:1347:11
    if (reset) begin	// <stdin>:1347:11
      io_alu_result_out_REG <= 32'h0;	// src/main/scala/core/Pipeline_Registers.scala:121:31
      io_write_data_out_REG <= 32'h0;	// src/main/scala/core/Pipeline_Registers.scala:121:31, :122:31
      io_rd_out_REG <= 5'h0;	// src/main/scala/core/Pipeline_Registers.scala:123:31
      io_mem_write_out_REG <= 1'h0;	// src/main/scala/core/Pipeline_Registers.scala:121:31, :125:31
      io_reg_write_out_REG <= 1'h0;	// src/main/scala/core/Pipeline_Registers.scala:121:31, :126:31
      io_mem_to_reg_out_REG <= 1'h0;	// src/main/scala/core/Pipeline_Registers.scala:121:31, :127:31
    end
    else begin	// <stdin>:1347:11
      io_alu_result_out_REG <= io_alu_result_in;	// src/main/scala/core/Pipeline_Registers.scala:121:31
      io_write_data_out_REG <= io_write_data_in;	// src/main/scala/core/Pipeline_Registers.scala:122:31
      io_rd_out_REG <= io_rd_in;	// src/main/scala/core/Pipeline_Registers.scala:123:31
      io_mem_write_out_REG <= io_mem_write_in;	// src/main/scala/core/Pipeline_Registers.scala:125:31
      io_reg_write_out_REG <= io_reg_write_in;	// src/main/scala/core/Pipeline_Registers.scala:126:31
      io_mem_to_reg_out_REG <= io_mem_to_reg_in;	// src/main/scala/core/Pipeline_Registers.scala:127:31
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/core/Pipeline_Registers.scala:102:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/core/Pipeline_Registers.scala:102:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/core/Pipeline_Registers.scala:102:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/core/Pipeline_Registers.scala:102:7
      automatic logic [31:0] _RANDOM[0:2];	// src/main/scala/core/Pipeline_Registers.scala:102:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/core/Pipeline_Registers.scala:102:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/core/Pipeline_Registers.scala:102:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/core/Pipeline_Registers.scala:102:7
        for (logic [1:0] i = 2'h0; i < 2'h3; i += 2'h1) begin
          _RANDOM[i] = `RANDOM;	// src/main/scala/core/Pipeline_Registers.scala:102:7
        end	// src/main/scala/core/Pipeline_Registers.scala:102:7
        io_alu_result_out_REG = _RANDOM[2'h0];	// src/main/scala/core/Pipeline_Registers.scala:102:7, :121:31
        io_write_data_out_REG = _RANDOM[2'h1];	// src/main/scala/core/Pipeline_Registers.scala:102:7, :122:31
        io_rd_out_REG = _RANDOM[2'h2][4:0];	// src/main/scala/core/Pipeline_Registers.scala:102:7, :123:31
        io_mem_write_out_REG = _RANDOM[2'h2][6];	// src/main/scala/core/Pipeline_Registers.scala:102:7, :123:31, :125:31
        io_reg_write_out_REG = _RANDOM[2'h2][7];	// src/main/scala/core/Pipeline_Registers.scala:102:7, :123:31, :126:31
        io_mem_to_reg_out_REG = _RANDOM[2'h2][8];	// src/main/scala/core/Pipeline_Registers.scala:102:7, :123:31, :127:31
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/core/Pipeline_Registers.scala:102:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/core/Pipeline_Registers.scala:102:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_alu_result_out = io_alu_result_out_REG;	// src/main/scala/core/Pipeline_Registers.scala:102:7, :121:31
  assign io_write_data_out = io_write_data_out_REG;	// src/main/scala/core/Pipeline_Registers.scala:102:7, :122:31
  assign io_rd_out = io_rd_out_REG;	// src/main/scala/core/Pipeline_Registers.scala:102:7, :123:31
  assign io_mem_write_out = io_mem_write_out_REG;	// src/main/scala/core/Pipeline_Registers.scala:102:7, :125:31
  assign io_reg_write_out = io_reg_write_out_REG;	// src/main/scala/core/Pipeline_Registers.scala:102:7, :126:31
  assign io_mem_to_reg_out = io_mem_to_reg_out_REG;	// src/main/scala/core/Pipeline_Registers.scala:102:7, :127:31
endmodule

module pipeline_reg_mem_wb(	// src/main/scala/core/Pipeline_Registers.scala:130:7
  input         clock,	// <stdin>:1374:11
                reset,	// <stdin>:1375:11
  input  [31:0] io_read_data_in,	// src/main/scala/core/Pipeline_Registers.scala:131:14
                io_alu_result_in,	// src/main/scala/core/Pipeline_Registers.scala:131:14
  input  [4:0]  io_rd_in,	// src/main/scala/core/Pipeline_Registers.scala:131:14
  input         io_reg_write_in,	// src/main/scala/core/Pipeline_Registers.scala:131:14
                io_mem_to_reg_in,	// src/main/scala/core/Pipeline_Registers.scala:131:14
  output [31:0] io_read_data_out,	// src/main/scala/core/Pipeline_Registers.scala:131:14
                io_alu_result_out,	// src/main/scala/core/Pipeline_Registers.scala:131:14
  output [4:0]  io_rd_out,	// src/main/scala/core/Pipeline_Registers.scala:131:14
  output        io_reg_write_out,	// src/main/scala/core/Pipeline_Registers.scala:131:14
                io_mem_to_reg_out	// src/main/scala/core/Pipeline_Registers.scala:131:14
);

  reg [31:0] io_read_data_out_REG;	// src/main/scala/core/Pipeline_Registers.scala:145:31
  reg [31:0] io_alu_result_out_REG;	// src/main/scala/core/Pipeline_Registers.scala:146:31
  reg [4:0]  io_rd_out_REG;	// src/main/scala/core/Pipeline_Registers.scala:147:31
  reg        io_reg_write_out_REG;	// src/main/scala/core/Pipeline_Registers.scala:148:31
  reg        io_mem_to_reg_out_REG;	// src/main/scala/core/Pipeline_Registers.scala:149:31
  always @(posedge clock) begin	// <stdin>:1374:11
    if (reset) begin	// <stdin>:1374:11
      io_read_data_out_REG <= 32'h0;	// src/main/scala/core/Pipeline_Registers.scala:145:31
      io_alu_result_out_REG <= 32'h0;	// src/main/scala/core/Pipeline_Registers.scala:145:31, :146:31
      io_rd_out_REG <= 5'h0;	// src/main/scala/core/Pipeline_Registers.scala:147:31
      io_reg_write_out_REG <= 1'h0;	// src/main/scala/core/Pipeline_Registers.scala:145:31, :148:31
      io_mem_to_reg_out_REG <= 1'h0;	// src/main/scala/core/Pipeline_Registers.scala:145:31, :149:31
    end
    else begin	// <stdin>:1374:11
      io_read_data_out_REG <= io_read_data_in;	// src/main/scala/core/Pipeline_Registers.scala:145:31
      io_alu_result_out_REG <= io_alu_result_in;	// src/main/scala/core/Pipeline_Registers.scala:146:31
      io_rd_out_REG <= io_rd_in;	// src/main/scala/core/Pipeline_Registers.scala:147:31
      io_reg_write_out_REG <= io_reg_write_in;	// src/main/scala/core/Pipeline_Registers.scala:148:31
      io_mem_to_reg_out_REG <= io_mem_to_reg_in;	// src/main/scala/core/Pipeline_Registers.scala:149:31
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/core/Pipeline_Registers.scala:130:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/core/Pipeline_Registers.scala:130:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/core/Pipeline_Registers.scala:130:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/core/Pipeline_Registers.scala:130:7
      automatic logic [31:0] _RANDOM[0:2];	// src/main/scala/core/Pipeline_Registers.scala:130:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/core/Pipeline_Registers.scala:130:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/core/Pipeline_Registers.scala:130:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/core/Pipeline_Registers.scala:130:7
        for (logic [1:0] i = 2'h0; i < 2'h3; i += 2'h1) begin
          _RANDOM[i] = `RANDOM;	// src/main/scala/core/Pipeline_Registers.scala:130:7
        end	// src/main/scala/core/Pipeline_Registers.scala:130:7
        io_read_data_out_REG = _RANDOM[2'h0];	// src/main/scala/core/Pipeline_Registers.scala:130:7, :145:31
        io_alu_result_out_REG = _RANDOM[2'h1];	// src/main/scala/core/Pipeline_Registers.scala:130:7, :146:31
        io_rd_out_REG = _RANDOM[2'h2][4:0];	// src/main/scala/core/Pipeline_Registers.scala:130:7, :147:31
        io_reg_write_out_REG = _RANDOM[2'h2][5];	// src/main/scala/core/Pipeline_Registers.scala:130:7, :147:31, :148:31
        io_mem_to_reg_out_REG = _RANDOM[2'h2][6];	// src/main/scala/core/Pipeline_Registers.scala:130:7, :147:31, :149:31
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/core/Pipeline_Registers.scala:130:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/core/Pipeline_Registers.scala:130:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_read_data_out = io_read_data_out_REG;	// src/main/scala/core/Pipeline_Registers.scala:130:7, :145:31
  assign io_alu_result_out = io_alu_result_out_REG;	// src/main/scala/core/Pipeline_Registers.scala:130:7, :146:31
  assign io_rd_out = io_rd_out_REG;	// src/main/scala/core/Pipeline_Registers.scala:130:7, :147:31
  assign io_reg_write_out = io_reg_write_out_REG;	// src/main/scala/core/Pipeline_Registers.scala:130:7, :148:31
  assign io_mem_to_reg_out = io_mem_to_reg_out_REG;	// src/main/scala/core/Pipeline_Registers.scala:130:7, :149:31
endmodule

module Hazard_Unit(	// src/main/scala/core/Hazard_Unit.scala:6:7
  input  [4:0] io_IF_ID_rs1,	// src/main/scala/core/Hazard_Unit.scala:7:14
               io_IF_ID_rs2,	// src/main/scala/core/Hazard_Unit.scala:7:14
               io_ID_EX_rd,	// src/main/scala/core/Hazard_Unit.scala:7:14
  input        io_ID_EX_MemRead,	// src/main/scala/core/Hazard_Unit.scala:7:14
  output       io_stall	// src/main/scala/core/Hazard_Unit.scala:7:14
);

  assign io_stall =
    io_ID_EX_MemRead & (io_ID_EX_rd == io_IF_ID_rs1 | io_ID_EX_rd == io_IF_ID_rs2);	// src/main/scala/core/Hazard_Unit.scala:6:7, :15:{25,42,60,76}
endmodule

module Forwarding_Unit(	// src/main/scala/core/Forwarding_Unit.scala:6:7
  input  [4:0] io_rs1_in,	// src/main/scala/core/Forwarding_Unit.scala:7:14
               io_rs2_in,	// src/main/scala/core/Forwarding_Unit.scala:7:14
  input        io_ex_mem_reg_write,	// src/main/scala/core/Forwarding_Unit.scala:7:14
  input  [4:0] io_ex_mem_rd,	// src/main/scala/core/Forwarding_Unit.scala:7:14
  input        io_mem_wb_reg_write,	// src/main/scala/core/Forwarding_Unit.scala:7:14
  input  [4:0] io_mem_wb_rd,	// src/main/scala/core/Forwarding_Unit.scala:7:14
  output [1:0] io_forward_a,	// src/main/scala/core/Forwarding_Unit.scala:7:14
               io_forward_b	// src/main/scala/core/Forwarding_Unit.scala:7:14
);

  wire _GEN = io_ex_mem_reg_write & (|io_ex_mem_rd);	// src/main/scala/core/Forwarding_Unit.scala:21:{28,45}
  wire _GEN_0 = io_mem_wb_reg_write & (|io_mem_wb_rd);	// src/main/scala/core/Forwarding_Unit.scala:23:{35,52}
  assign io_forward_a =
    _GEN & io_ex_mem_rd == io_rs1_in ? 2'h2 : {1'h0, _GEN_0 & io_mem_wb_rd == io_rs1_in};	// src/main/scala/core/Forwarding_Unit.scala:6:7, :18:21, :21:{28,54,71,87}, :22:9, :23:{35,61,78,94}, :24:9
  assign io_forward_b =
    _GEN & io_ex_mem_rd == io_rs2_in ? 2'h2 : {1'h0, _GEN_0 & io_mem_wb_rd == io_rs2_in};	// src/main/scala/core/Forwarding_Unit.scala:6:7, :18:21, :19:21, :21:28, :22:9, :23:{35,94}, :24:9, :27:{54,71,87}, :28:9, :29:{61,78,94}, :30:9
endmodule

module Top(	// src/main/scala/core/Top.scala:7:7
  input  clock,	// <stdin>:1448:11
         reset,	// <stdin>:1449:11
  output io_exit	// src/main/scala/core/Top.scala:8:14
);

  wire [31:0] write_back_data;	// src/main/scala/core/Top.scala:127:25
  wire [1:0]  _forward_io_forward_a;	// src/main/scala/core/Top.scala:30:26
  wire [1:0]  _forward_io_forward_b;	// src/main/scala/core/Top.scala:30:26
  wire        _hazard_io_stall;	// src/main/scala/core/Top.scala:29:26
  wire [31:0] _mem_wb_io_read_data_out;	// src/main/scala/core/Top.scala:27:26
  wire [31:0] _mem_wb_io_alu_result_out;	// src/main/scala/core/Top.scala:27:26
  wire [4:0]  _mem_wb_io_rd_out;	// src/main/scala/core/Top.scala:27:26
  wire        _mem_wb_io_reg_write_out;	// src/main/scala/core/Top.scala:27:26
  wire        _mem_wb_io_mem_to_reg_out;	// src/main/scala/core/Top.scala:27:26
  wire [31:0] _ex_mem_io_alu_result_out;	// src/main/scala/core/Top.scala:26:26
  wire [31:0] _ex_mem_io_write_data_out;	// src/main/scala/core/Top.scala:26:26
  wire [4:0]  _ex_mem_io_rd_out;	// src/main/scala/core/Top.scala:26:26
  wire        _ex_mem_io_mem_write_out;	// src/main/scala/core/Top.scala:26:26
  wire        _ex_mem_io_reg_write_out;	// src/main/scala/core/Top.scala:26:26
  wire        _ex_mem_io_mem_to_reg_out;	// src/main/scala/core/Top.scala:26:26
  wire [31:0] _id_ex_io_read_data1_out;	// src/main/scala/core/Top.scala:25:26
  wire [31:0] _id_ex_io_read_data2_out;	// src/main/scala/core/Top.scala:25:26
  wire [31:0] _id_ex_io_sign_ext_imm_out;	// src/main/scala/core/Top.scala:25:26
  wire [4:0]  _id_ex_io_rd_out;	// src/main/scala/core/Top.scala:25:26
  wire [4:0]  _id_ex_io_rs1_out;	// src/main/scala/core/Top.scala:25:26
  wire [4:0]  _id_ex_io_rs2_out;	// src/main/scala/core/Top.scala:25:26
  wire        _id_ex_io_ALU_src_out;	// src/main/scala/core/Top.scala:25:26
  wire [3:0]  _id_ex_io_ALU_op_out;	// src/main/scala/core/Top.scala:25:26
  wire        _id_ex_io_mem_write_out;	// src/main/scala/core/Top.scala:25:26
  wire        _id_ex_io_mem_read_out;	// src/main/scala/core/Top.scala:25:26
  wire        _id_ex_io_reg_write_out;	// src/main/scala/core/Top.scala:25:26
  wire        _id_ex_io_mem_to_reg_out;	// src/main/scala/core/Top.scala:25:26
  wire [31:0] _if_id_io_instruction_out;	// src/main/scala/core/Top.scala:24:26
  wire [31:0] _dmem_io_read_data;	// src/main/scala/core/Top.scala:22:26
  wire [31:0] _alu_io_alu_result;	// src/main/scala/core/Top.scala:21:26
  wire [31:0] _immGen_io_imm;	// src/main/scala/core/Top.scala:20:26
  wire        _control_io_ALU_src;	// src/main/scala/core/Top.scala:19:26
  wire        _control_io_Reg_write;	// src/main/scala/core/Top.scala:19:26
  wire        _control_io_Mem_write;	// src/main/scala/core/Top.scala:19:26
  wire        _control_io_MemRead;	// src/main/scala/core/Top.scala:19:26
  wire [3:0]  _control_io_ALU_op;	// src/main/scala/core/Top.scala:19:26
  wire        _control_io_MemtoReg;	// src/main/scala/core/Top.scala:19:26
  wire [31:0] _regFile_io_rd1;	// src/main/scala/core/Top.scala:18:26
  wire [31:0] _regFile_io_rd2;	// src/main/scala/core/Top.scala:18:26
  wire [31:0] _imem_io_data_out;	// src/main/scala/core/Top.scala:17:26
  wire [31:0] _pc_reg_io_pc_out;	// src/main/scala/core/Top.scala:16:26
  wire [31:0] forward_b_mux =
    _forward_io_forward_b == 2'h2
      ? _ex_mem_io_alu_result_out
      : _forward_io_forward_b == 2'h1 ? write_back_data : _id_ex_io_read_data2_out;	// src/main/scala/core/Top.scala:25:26, :26:26, :30:26, :88:74, :94:79, :127:25
  assign write_back_data =
    _mem_wb_io_mem_to_reg_out ? _mem_wb_io_read_data_out : _mem_wb_io_alu_result_out;	// src/main/scala/core/Top.scala:27:26, :127:25
  PC pc_reg (	// src/main/scala/core/Top.scala:16:26
    .clock     (clock),
    .reset     (reset),
    .io_pc_in  (_pc_reg_io_pc_out + 32'h4),	// src/main/scala/core/Top.scala:16:26, :34:36
    .io_stall  (_hazard_io_stall),	// src/main/scala/core/Top.scala:29:26
    .io_pc_out (_pc_reg_io_pc_out)
  );
  InstructionMemory imem (	// src/main/scala/core/Top.scala:17:26
    .io_address  (_pc_reg_io_pc_out),	// src/main/scala/core/Top.scala:16:26
    .io_data_out (_imem_io_data_out)
  );
  RegisterFile regFile (	// src/main/scala/core/Top.scala:18:26
    .clock       (clock),
    .reset       (reset),
    .io_regWrite (_mem_wb_io_reg_write_out),	// src/main/scala/core/Top.scala:27:26
    .io_ra1      (_if_id_io_instruction_out[19:15]),	// src/main/scala/core/Top.scala:24:26, :53:28
    .io_ra2      (_if_id_io_instruction_out[24:20]),	// src/main/scala/core/Top.scala:24:26, :54:28
    .io_wa       (_mem_wb_io_rd_out),	// src/main/scala/core/Top.scala:27:26
    .io_wd       (write_back_data),	// src/main/scala/core/Top.scala:127:25
    .io_rd1      (_regFile_io_rd1),
    .io_rd2      (_regFile_io_rd2)
  );
  Control_Unit control (	// src/main/scala/core/Top.scala:19:26
    .io_instruction (_if_id_io_instruction_out),	// src/main/scala/core/Top.scala:24:26
    .io_stall       (_hazard_io_stall),	// src/main/scala/core/Top.scala:29:26
    .io_ALU_src     (_control_io_ALU_src),
    .io_Reg_write   (_control_io_Reg_write),
    .io_Mem_write   (_control_io_Mem_write),
    .io_MemRead     (_control_io_MemRead),
    .io_ALU_op      (_control_io_ALU_op),
    .io_MemtoReg    (_control_io_MemtoReg)
  );
  ImmGen immGen (	// src/main/scala/core/Top.scala:20:26
    .io_instr (_if_id_io_instruction_out),	// src/main/scala/core/Top.scala:24:26
    .io_imm   (_immGen_io_imm)
  );
  ALU alu (	// src/main/scala/core/Top.scala:21:26
    .io_op1
      (_forward_io_forward_a == 2'h2
         ? _ex_mem_io_alu_result_out
         : _forward_io_forward_a == 2'h1 ? write_back_data : _id_ex_io_read_data1_out),	// src/main/scala/core/Top.scala:25:26, :26:26, :30:26, :88:74, :127:25
    .io_op2         (_id_ex_io_ALU_src_out ? _id_ex_io_sign_ext_imm_out : forward_b_mux),	// src/main/scala/core/Top.scala:25:26, :94:79, :101:28
    .io_alu_control (_id_ex_io_ALU_op_out),	// src/main/scala/core/Top.scala:25:26
    .io_alu_result  (_alu_io_alu_result)
  );
  Data_Memory dmem (	// src/main/scala/core/Top.scala:22:26
    .clock         (clock),
    .io_Daddress   (_ex_mem_io_alu_result_out),	// src/main/scala/core/Top.scala:26:26
    .io_write_data (_ex_mem_io_write_data_out),	// src/main/scala/core/Top.scala:26:26
    .io_MemWrite   (_ex_mem_io_mem_write_out),	// src/main/scala/core/Top.scala:26:26
    .io_read_data  (_dmem_io_read_data)
  );
  pipeline_reg_if_id if_id (	// src/main/scala/core/Top.scala:24:26
    .clock              (clock),
    .reset              (reset),
    .io_stall           (_hazard_io_stall),	// src/main/scala/core/Top.scala:29:26
    .io_instruction_in  (_imem_io_data_out),	// src/main/scala/core/Top.scala:17:26
    .io_instruction_out (_if_id_io_instruction_out)
  );
  pipeline_reg_id_ex id_ex (	// src/main/scala/core/Top.scala:25:26
    .clock               (clock),
    .reset               (reset),
    .io_flush            (_hazard_io_stall),	// src/main/scala/core/Top.scala:29:26
    .io_read_data1_in    (_regFile_io_rd1),	// src/main/scala/core/Top.scala:18:26
    .io_read_data2_in    (_regFile_io_rd2),	// src/main/scala/core/Top.scala:18:26
    .io_sign_ext_imm_in  (_immGen_io_imm),	// src/main/scala/core/Top.scala:20:26
    .io_rd_in            (_if_id_io_instruction_out[11:7]),	// src/main/scala/core/Top.scala:24:26, :67:39
    .io_rs1_in           (_if_id_io_instruction_out[19:15]),	// src/main/scala/core/Top.scala:24:26, :53:28
    .io_rs2_in           (_if_id_io_instruction_out[24:20]),	// src/main/scala/core/Top.scala:24:26, :54:28
    .io_ALU_src_in       (_control_io_ALU_src),	// src/main/scala/core/Top.scala:19:26
    .io_ALU_op_in        (_control_io_ALU_op),	// src/main/scala/core/Top.scala:19:26
    .io_mem_write_in     (_control_io_Mem_write),	// src/main/scala/core/Top.scala:19:26
    .io_mem_read_in      (_control_io_MemRead),	// src/main/scala/core/Top.scala:19:26
    .io_reg_write_in     (_control_io_Reg_write),	// src/main/scala/core/Top.scala:19:26
    .io_mem_to_reg_in    (_control_io_MemtoReg),	// src/main/scala/core/Top.scala:19:26
    .io_read_data1_out   (_id_ex_io_read_data1_out),
    .io_read_data2_out   (_id_ex_io_read_data2_out),
    .io_sign_ext_imm_out (_id_ex_io_sign_ext_imm_out),
    .io_rd_out           (_id_ex_io_rd_out),
    .io_rs1_out          (_id_ex_io_rs1_out),
    .io_rs2_out          (_id_ex_io_rs2_out),
    .io_ALU_src_out      (_id_ex_io_ALU_src_out),
    .io_ALU_op_out       (_id_ex_io_ALU_op_out),
    .io_mem_write_out    (_id_ex_io_mem_write_out),
    .io_mem_read_out     (_id_ex_io_mem_read_out),
    .io_reg_write_out    (_id_ex_io_reg_write_out),
    .io_mem_to_reg_out   (_id_ex_io_mem_to_reg_out)
  );
  pipeline_reg_ex_mem ex_mem (	// src/main/scala/core/Top.scala:26:26
    .clock             (clock),
    .reset             (reset),
    .io_alu_result_in  (_alu_io_alu_result),	// src/main/scala/core/Top.scala:21:26
    .io_write_data_in  (forward_b_mux),	// src/main/scala/core/Top.scala:94:79
    .io_rd_in          (_id_ex_io_rd_out),	// src/main/scala/core/Top.scala:25:26
    .io_mem_write_in   (_id_ex_io_mem_write_out),	// src/main/scala/core/Top.scala:25:26
    .io_reg_write_in   (_id_ex_io_reg_write_out),	// src/main/scala/core/Top.scala:25:26
    .io_mem_to_reg_in  (_id_ex_io_mem_to_reg_out),	// src/main/scala/core/Top.scala:25:26
    .io_alu_result_out (_ex_mem_io_alu_result_out),
    .io_write_data_out (_ex_mem_io_write_data_out),
    .io_rd_out         (_ex_mem_io_rd_out),
    .io_mem_write_out  (_ex_mem_io_mem_write_out),
    .io_reg_write_out  (_ex_mem_io_reg_write_out),
    .io_mem_to_reg_out (_ex_mem_io_mem_to_reg_out)
  );
  pipeline_reg_mem_wb mem_wb (	// src/main/scala/core/Top.scala:27:26
    .clock             (clock),
    .reset             (reset),
    .io_read_data_in   (_dmem_io_read_data),	// src/main/scala/core/Top.scala:22:26
    .io_alu_result_in  (_ex_mem_io_alu_result_out),	// src/main/scala/core/Top.scala:26:26
    .io_rd_in          (_ex_mem_io_rd_out),	// src/main/scala/core/Top.scala:26:26
    .io_reg_write_in   (_ex_mem_io_reg_write_out),	// src/main/scala/core/Top.scala:26:26
    .io_mem_to_reg_in  (_ex_mem_io_mem_to_reg_out),	// src/main/scala/core/Top.scala:26:26
    .io_read_data_out  (_mem_wb_io_read_data_out),
    .io_alu_result_out (_mem_wb_io_alu_result_out),
    .io_rd_out         (_mem_wb_io_rd_out),
    .io_reg_write_out  (_mem_wb_io_reg_write_out),
    .io_mem_to_reg_out (_mem_wb_io_mem_to_reg_out)
  );
  Hazard_Unit hazard (	// src/main/scala/core/Top.scala:29:26
    .io_IF_ID_rs1     (_if_id_io_instruction_out[19:15]),	// src/main/scala/core/Top.scala:24:26, :53:28
    .io_IF_ID_rs2     (_if_id_io_instruction_out[24:20]),	// src/main/scala/core/Top.scala:24:26, :54:28
    .io_ID_EX_rd      (_id_ex_io_rd_out),	// src/main/scala/core/Top.scala:25:26
    .io_ID_EX_MemRead (_id_ex_io_mem_read_out),	// src/main/scala/core/Top.scala:25:26
    .io_stall         (_hazard_io_stall)
  );
  Forwarding_Unit forward (	// src/main/scala/core/Top.scala:30:26
    .io_rs1_in           (_id_ex_io_rs1_out),	// src/main/scala/core/Top.scala:25:26
    .io_rs2_in           (_id_ex_io_rs2_out),	// src/main/scala/core/Top.scala:25:26
    .io_ex_mem_reg_write (_ex_mem_io_reg_write_out),	// src/main/scala/core/Top.scala:26:26
    .io_ex_mem_rd        (_ex_mem_io_rd_out),	// src/main/scala/core/Top.scala:26:26
    .io_mem_wb_reg_write (_mem_wb_io_reg_write_out),	// src/main/scala/core/Top.scala:27:26
    .io_mem_wb_rd        (_mem_wb_io_rd_out),	// src/main/scala/core/Top.scala:27:26
    .io_forward_a        (_forward_io_forward_a),
    .io_forward_b        (_forward_io_forward_b)
  );
  assign io_exit = _alu_io_alu_result[0];	// src/main/scala/core/Top.scala:7:7, :21:26, :103:31
endmodule

